FROM python:3.8.5

RUN apt-get update && \
    apt-get install -y bash jq && \
    pip install mypy==0.770 mypy2junit pytest

ADD .jenkins/run_mypy.sh /bin

ADD .jenkins/Ampel-interface /src/Ampel-interface
ADD .jenkins/Ampel-core /src/Ampel-core
ADD .jenkins/Ampel-alerts /src/Ampel-alerts
ADD .jenkins/Ampel-photometry /src/Ampel-photometry
RUN pip install /src/Ampel-*

ADD . /
RUN cd / && pip install -e .[testing]
