FROM python:3.8.5

RUN apt-get update && \
    apt-get install -y bash jq && \
    pip install mypy==0.770 mypy2junit pytest

ADD .jenkins/run_mypy.sh /bin

ADD . /build
RUN cd /build && pip install \
    .jenkins/Ampel-interface \
    .jenkins/Ampel-core \
    .jenkins/Ampel-photometry \
    .jenkins/Ampel-alerts \
    -e .[testing]

