name: ci

on:
  push:
    branches:
      - main
      - renovate/*
      - dev/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - dev/*
      - stable/*

jobs:
  ci:
    uses: AmpelProject/Ampel-interface/.github/workflows/ci.yml@c98c2c46f4a95fed0608429754e9f285ac21238e # ci-py12-v6
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    with:
      mongo: false
      lint: true
      format: true
      # renovate: datasource=python-version depName=python versioning=python
      python-version: "3.13.1"
      # renovate: datasource=pypi depName=ruff
      ruff-version: "0.8.6"
